# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_laas')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_laas')
    _laas = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_laas', [dirname(__file__)])
        except ImportError:
            import _laas
            return _laas
        try:
            _mod = imp.load_module('_laas', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _laas = swig_import_helper()
    del swig_import_helper
else:
    import _laas
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _laas.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _laas.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _laas.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _laas.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _laas.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _laas.SwigPyIterator_equal(self, x)

    def copy(self):
        return _laas.SwigPyIterator_copy(self)

    def next(self):
        return _laas.SwigPyIterator_next(self)

    def __next__(self):
        return _laas.SwigPyIterator___next__(self)

    def previous(self):
        return _laas.SwigPyIterator_previous(self)

    def advance(self, n):
        return _laas.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _laas.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _laas.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _laas.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _laas.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _laas.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _laas.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _laas.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VecInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _laas.VecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _laas.VecInt___nonzero__(self)

    def __bool__(self):
        return _laas.VecInt___bool__(self)

    def __len__(self):
        return _laas.VecInt___len__(self)

    def __getslice__(self, i, j):
        return _laas.VecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _laas.VecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _laas.VecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _laas.VecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _laas.VecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _laas.VecInt___setitem__(self, *args)

    def pop(self):
        return _laas.VecInt_pop(self)

    def append(self, x):
        return _laas.VecInt_append(self, x)

    def empty(self):
        return _laas.VecInt_empty(self)

    def size(self):
        return _laas.VecInt_size(self)

    def swap(self, v):
        return _laas.VecInt_swap(self, v)

    def begin(self):
        return _laas.VecInt_begin(self)

    def end(self):
        return _laas.VecInt_end(self)

    def rbegin(self):
        return _laas.VecInt_rbegin(self)

    def rend(self):
        return _laas.VecInt_rend(self)

    def clear(self):
        return _laas.VecInt_clear(self)

    def get_allocator(self):
        return _laas.VecInt_get_allocator(self)

    def pop_back(self):
        return _laas.VecInt_pop_back(self)

    def erase(self, *args):
        return _laas.VecInt_erase(self, *args)

    def __init__(self, *args):
        this = _laas.new_VecInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _laas.VecInt_push_back(self, x)

    def front(self):
        return _laas.VecInt_front(self)

    def back(self):
        return _laas.VecInt_back(self)

    def assign(self, n, x):
        return _laas.VecInt_assign(self, n, x)

    def resize(self, *args):
        return _laas.VecInt_resize(self, *args)

    def insert(self, *args):
        return _laas.VecInt_insert(self, *args)

    def reserve(self, n):
        return _laas.VecInt_reserve(self, n)

    def capacity(self):
        return _laas.VecInt_capacity(self)
    __swig_destroy__ = _laas.delete_VecInt
    __del__ = lambda self: None
VecInt_swigregister = _laas.VecInt_swigregister
VecInt_swigregister(VecInt)

class PairInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PairInt, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _laas.new_PairInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["first"] = _laas.PairInt_first_set
    __swig_getmethods__["first"] = _laas.PairInt_first_get
    if _newclass:
        first = _swig_property(_laas.PairInt_first_get, _laas.PairInt_first_set)
    __swig_setmethods__["second"] = _laas.PairInt_second_set
    __swig_getmethods__["second"] = _laas.PairInt_second_get
    if _newclass:
        second = _swig_property(_laas.PairInt_second_get, _laas.PairInt_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _laas.delete_PairInt
    __del__ = lambda self: None
PairInt_swigregister = _laas.PairInt_swigregister
PairInt_swigregister(PairInt)

class VecPairInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecPairInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecPairInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _laas.VecPairInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _laas.VecPairInt___nonzero__(self)

    def __bool__(self):
        return _laas.VecPairInt___bool__(self)

    def __len__(self):
        return _laas.VecPairInt___len__(self)

    def __getslice__(self, i, j):
        return _laas.VecPairInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _laas.VecPairInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _laas.VecPairInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _laas.VecPairInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _laas.VecPairInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _laas.VecPairInt___setitem__(self, *args)

    def pop(self):
        return _laas.VecPairInt_pop(self)

    def append(self, x):
        return _laas.VecPairInt_append(self, x)

    def empty(self):
        return _laas.VecPairInt_empty(self)

    def size(self):
        return _laas.VecPairInt_size(self)

    def swap(self, v):
        return _laas.VecPairInt_swap(self, v)

    def begin(self):
        return _laas.VecPairInt_begin(self)

    def end(self):
        return _laas.VecPairInt_end(self)

    def rbegin(self):
        return _laas.VecPairInt_rbegin(self)

    def rend(self):
        return _laas.VecPairInt_rend(self)

    def clear(self):
        return _laas.VecPairInt_clear(self)

    def get_allocator(self):
        return _laas.VecPairInt_get_allocator(self)

    def pop_back(self):
        return _laas.VecPairInt_pop_back(self)

    def erase(self, *args):
        return _laas.VecPairInt_erase(self, *args)

    def __init__(self, *args):
        this = _laas.new_VecPairInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _laas.VecPairInt_push_back(self, x)

    def front(self):
        return _laas.VecPairInt_front(self)

    def back(self):
        return _laas.VecPairInt_back(self)

    def assign(self, n, x):
        return _laas.VecPairInt_assign(self, n, x)

    def resize(self, *args):
        return _laas.VecPairInt_resize(self, *args)

    def insert(self, *args):
        return _laas.VecPairInt_insert(self, *args)

    def reserve(self, n):
        return _laas.VecPairInt_reserve(self, n)

    def capacity(self):
        return _laas.VecPairInt_capacity(self)
    __swig_destroy__ = _laas.delete_VecPairInt
    __del__ = lambda self: None
VecPairInt_swigregister = _laas.VecPairInt_swigregister
VecPairInt_swigregister(VecPairInt)

class SetInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SetInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SetInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _laas.SetInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _laas.SetInt___nonzero__(self)

    def __bool__(self):
        return _laas.SetInt___bool__(self)

    def __len__(self):
        return _laas.SetInt___len__(self)

    def append(self, x):
        return _laas.SetInt_append(self, x)

    def __contains__(self, x):
        return _laas.SetInt___contains__(self, x)

    def __getitem__(self, i):
        return _laas.SetInt___getitem__(self, i)

    def add(self, x):
        return _laas.SetInt_add(self, x)

    def discard(self, x):
        return _laas.SetInt_discard(self, x)

    def __init__(self, *args):
        this = _laas.new_SetInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def empty(self):
        return _laas.SetInt_empty(self)

    def size(self):
        return _laas.SetInt_size(self)

    def clear(self):
        return _laas.SetInt_clear(self)

    def swap(self, v):
        return _laas.SetInt_swap(self, v)

    def count(self, x):
        return _laas.SetInt_count(self, x)

    def begin(self):
        return _laas.SetInt_begin(self)

    def end(self):
        return _laas.SetInt_end(self)

    def rbegin(self):
        return _laas.SetInt_rbegin(self)

    def rend(self):
        return _laas.SetInt_rend(self)

    def erase(self, *args):
        return _laas.SetInt_erase(self, *args)

    def find(self, x):
        return _laas.SetInt_find(self, x)

    def lower_bound(self, x):
        return _laas.SetInt_lower_bound(self, x)

    def upper_bound(self, x):
        return _laas.SetInt_upper_bound(self, x)

    def equal_range(self, x):
        return _laas.SetInt_equal_range(self, x)

    def insert(self, __x):
        return _laas.SetInt_insert(self, __x)
    __swig_destroy__ = _laas.delete_SetInt
    __del__ = lambda self: None
SetInt_swigregister = _laas.SetInt_swigregister
SetInt_swigregister(SetInt)

class LaaS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LaaS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LaaS, name)
    __repr__ = _swig_repr

    def __init__(self, M, W, logFileName):
        this = _laas.new_LaaS(M, W, logFileName)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def good(self):
        return _laas.LaaS_good(self)

    def getLastErrorMsg(self):
        return _laas.LaaS_getLastErrorMsg(self)

    def setVerbose(self, v):
        return _laas.LaaS_setVerbose(self, v)

    def replayLogFile(self):
        return _laas.LaaS_replayLogFile(self)

    def getUnAllocated(self, hosts, l1UpPorts, l2UpPorts):
        return _laas.LaaS_getUnAllocated(self, hosts, l1UpPorts, l2UpPorts)

    def getTenants(self, tenantIds):
        return _laas.LaaS_getTenants(self, tenantIds)

    def getTenantAlloc(self, tenantId, hosts, l1UpPorts, l2UpPorts):
        return _laas.LaaS_getTenantAlloc(self, tenantId, hosts, l1UpPorts, l2UpPorts)

    def allocTenant(self, tenantId, GroupHosts):
        return _laas.LaaS_allocTenant(self, tenantId, GroupHosts)

    def assignTenant(self, tenantId, hosts, l1UpPorts, l2UpPorts):
        return _laas.LaaS_assignTenant(self, tenantId, hosts, l1UpPorts, l2UpPorts)

    def deallocTenant(self, tenantId):
        return _laas.LaaS_deallocTenant(self, tenantId)

    def setLeafGroup(self, group, leafIdxs):
        return _laas.LaaS_setLeafGroup(self, group, leafIdxs)

    def setLeafCost(self, group, leafIdxs):
        return _laas.LaaS_setLeafCost(self, group, leafIdxs)
    __swig_destroy__ = _laas.delete_LaaS
    __del__ = lambda self: None
LaaS_swigregister = _laas.LaaS_swigregister
LaaS_swigregister(LaaS)

# This file is compatible with both classic and new-style classes.


